---
title: "Programming Assignment 2"
author: "Michele Goldin"
date: "1/30/2018"
output: 
  html_document: 
    highlight: kate
    keep_md: yes
    theme: united
---

## Plot 1

```{r}
library(languageR)
library(tidyverse)

beginningReaders %>%
  select(., LogFrequency, Word) %>%
  ggplot(., aes(x = as.factor(Word), y = LogFrequency)) +
  geom_point()+
  labs(x="Word", y = "Log Frequency", title = "My Beginning Readers Scatterplot")
caption = "Log Frequency as a function of Word"

```

## Plot2

```{r}
english %>%
  ggplot(., aes(x = as.factor(AgeSubject), y = as.factor(Frication), color = VerbFrequency)) +
  geom_boxplot() +
  labs(x="Age", y = "Frication", title = "My English Boxplot")
caption = "My Boxplot"

```


##P lot3

```{r}
danish %>%
ggplot(., aes(x = as.factor(Subject), y = LogRT)) +
  stat_summary(fun.data = mean_cl_boot, geom = 'pointrange') + 
  facet_grid(. ~ Sex) +
  labs(x="Participants", y = "Reading Times", title = "My Danish Plot")
caption = "Reading Times distributed by Sex"

```