---
title: "Pa2"
author: "Esther Hur"
date: "Last update: 2018-01-29 18:20:58"
output: 
  html_document: 
  highlight: kate
keep_md: yes
theme: united
---

 ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---
```{r}
library(languageR)
library(tidyverse)
library(ggplot2)
library(dplyr)


str(beginningReaders)
str(danish)
str(dativeSimplified)
str(spanishFunctionWords)
str(english)


# Inside your pa2.Rmd file you will generate 3 different plots using
# ggplot2. You must use 3 of the aforementioned datasets (a different
# dataset for each plot). All plots must include informative x-, y-axis
# labels and a title. The plots you must create are:
#
# A bivariate scatterplot
# A boxplot with different fill colors
# A plot of your choice that includes a stat_summary and a facet.


# 1st plot
ggplot(data = danish, aes(x = LogCUP, y = LogWordFreq)) +
    geom_point() +
    labs(x = 'LogCUP', y = 'Word Frequency', 
         title = 'Danish boxplot')


# 2nd plot
ggplot(data = dativeSimplified, aes(x = AnimacyOfRec, y = LengthOfTheme, fill = AnimacyOfRec)) + 
  geom_boxplot()
  labs(x = 'AnimacyOfRec', y = 'LengthOfTheme', title= 'My boxplot')
  

# 3rd plot
ggplot(data = english, aes(x = RTnaming, y = WrittenFrequency)) +
  stat_summary(fun.data = mean_cl_boot, geom = 'pointrange') + 
  facet_wrap(~ AgeSubject) +
  labs(x = 'RTnaming', y = 'WrittenFrequency', title= 'English')
  
```